[modules]
  [modules.preprocessor]
    name = "blockchaintable.TransferPreparer"
    path = "blockchaintable-test/build/libs/blockchaintable-test-all.jar"
  [modules.processor]
    name = "blockchaintable.TransferProcessor"
    path = "blockchaintable-test/build/libs/blockchaintable-test-all.jar"
  [modules.postprocessor]
    name = "blockchaintable.TransferReporter"
    path = "blockchaintable-test/build/libs/blockchaintable-test-all.jar"

[common]
  concurrency = 4
  run_for_sec = 100
  ramp_for_sec = 10
  injection_executor = "com.scalar.kelpie.executor.OnetimeInjectionExecutor"

[blockchaintable_test]
  title = "Blockchaintable test"
  num_accounts = 10000
  url = "jdbc:oracle:thin:@//localhost/XEPDB1"
  user = "scalar"
  password = "scalar"
  conn_factory_class_name = "oracle.jdbc.pool.OracleDataSource"
  initial_pool_size = 5
  min_pool_size = 5
  max_pool_size = 20


  